### PR TITLE
Menu re-hides itself when not in use

### PR DESCRIPTION
**Pull request by Pater1**
Implemented the menu sliding back out of frame when the mouse is no longer over the menu div.

### CODE REVIEW

**Comment by connerk** [comment]
well I like it... 😄 
it's a bit abrupt though.
any chance at one of the two:
a 200ms or so delay.
act based on scroll or click input rather than hover?

**Comment by pcunning** [comment]
CSS transitions will do this if we add them to the class.

**Comment by connerk** [comment]
What?! but no $() ?!?!?

**Comment by Pater1** [comment]
CSS Animations would work for this. I'm on it now...

**Comment by connerk** [comment]
are you able to close it yourself without a merge @Pater1?

**Comment by Pater1** [comment]
A) Added 400ms delay to closing menu after mouse leave (not using CSS animations, but setTimeout, if you're curious).

B) @connerk able to close what?

**Comment by Pater1** [comment]
Updated the variable name.

**Pull request closed without merging**
